### ISSUE TITLE
Theme Settings link should point to new theme customizer option

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Travelify#11]
The Theme Settings link as shown in the attached screenshot should point to new theme customizer option instead of old theme options.
![screenshot 3](https://cloud.githubusercontent.com/assets/11946142/11145056/e343d538-8a27-11e5-9565-e359579453c2.png)

**Comment by puikinsh** [comment]
Fixed on https://github.com/puikinsh/Travelify/pull/15
