### ISSUE TITLE
Remove the default menu item "Navigation" from the header menu

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Travelify#12]
Related topics : 
https://colorlib.com/wp/forums/topic/delete-tab-navigation-menu-bar/
https://colorlib.com/wp/forums/topic/update-to-travelify-3-0-gives-additional-menu-item/
https://colorlib.com/wp/forums/topic/nav-bar-and-header-problems/

**Comment by puikinsh** [comment]
Fixed version for this theme is already live on WordPress.org

**Comment by FreeWPTP** [comment]
The issue is resolved by deleting the existing theme and using latest version of it from WordPress.org
