### ISSUE TITLE
Display Shortcodes In Excerpt

### ISSUE THREAD

**Issue by samuelhurley** [puikinsh/Travelify#2]
I am trying to display shortcodes in the excerpt previews of articles on the front page of my site.

Per other instructions I have included the following lines in the theme's functions.php file. However this has no effect on the preview posts that show up on my front page. I have made sure that the shortcode is before the  tag in the article. Any help would be greatly appreciated.

    add_filter('the_excerpt',  'shortcode_unautop');
    add_filter('the_excerpt',  'do_shortcode');

**Comment by puikinsh** [comment]
Hey, 

Sorry for late response. Somehow missed this issue. 

Your solution is correct but it will work only when you add your shortcode inside Excerpt field that you can see under Post editor screen but it won't do a thing for automatically generated ones. For that you can use function like this: 

```
add_filter('the_excerpt', 'travelify_shortcode_in_excerpt');
function travelify_shortcode_in_excerpt($excerpt) {
    return do_shortcode(wp_trim_words(get_the_content(), 55));
}
```

Let me know if this is what you were looking for.

**Comment by samuelhurley** [comment]
Hi Aigars,

Awesome! This is exactly what I was working for. Thank you very much for
your help, it is greatly appreciated.

Best wishes,
-Sam

---
Samuel A. Hurley, PhD
MRI Physics Support Scientist
FMRIB Centre, University of Oxford
Telephone:  +44 (0) 1865 589 608
http://users.fmrib.ox.ac.uk/~shurley/
