### ISSUE TITLE
Feature Request - Allow user to set site background color in the customizer

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Travelify#9]
There was an option to set the background color as mentioned in the section “3. Custom Background” on the following page.

https://colorlib.com/wp/support/travelify/

But in the latest version of the theme there is only the option to set background image on the following path and not the background color.

Admin Area -> Apperance -> Customize -> Background Image

**Comment by puikinsh** [comment]
Background image can be changed under Appearance -> Customize -> Colors -> Background. But first user should remove background image as it comes on top of background color.

**Comment by FreeWPTP** [comment]
Thanks. I got it.
